### ISSUE TITLE
CSP rules in preload bundle for iOS blocking the connection to backend servers web socket

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/playcanvas-rest-api-tools#31]
Since a few days we are racking our brains around the issue with iOS devices are not able to connect to web socket in sc. Today we figured out that the problem appears after we updated the playcanvas-rest-api-tools till latest version where csp rules were added to preload bundles. 
After a while we rolled back to the #26 and had no issues with iOS devices and backend.

**Comment by yaustar** [comment]
Interesting, adding CSP rules to the preload bundles broke access completely? 🤔 

If the line `then(updatePreloadBundles)` in the file csp-patch.js, does it work?

**Comment by flyingbaba** [comment]
> Interesting, adding CSP rules to the preload bundles broke access completely?

socket.connect was firing an error. It is a bit hard for us to debug as we do not have Mac. I'm using remotedebug_ios_webkit_adapter to debug with iphone but in sc it is not possible. So I have to create a build in playcanvas to test and dev console. But issue like this one was really hard to find. 

> If the line then(updatePreloadBundles) is removed in the file csp-patch.js, does it work?

Yes. 

Thanks for the side notes 👍

**Comment by yaustar** [comment]
I can't reproduce the error on my test project with Bitmoji Plaza and haven't yet had any other reports. I may add a flag to patch preload bundles for the short term until I hear more.

**Comment by yaustar** [comment]
I just found out there was a bug in my implementation of this and it added an extra bit of text in the CSP meta that could be invalidating it. I've updated master to fix this so might be worth another go with adding CSP rules to preload bundles? N
