### ISSUE TITLE
Add an ability to strip localStorage mentioning in the code

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/playcanvas-rest-api-tools#38]
While trying to make a valid build for [Google HTML5 validator](https://h5validator.appspot.com/dcm/asset) we had an issue / blocker with `Advanced HTML check` . 

Here is the details: 
```
One of your HTML5 assets is invalid and cannot be analyzed. Please correct any malformed assets and try again.

More details:
Source: HTML5_FEATURE_UNSUPPORTED found in playable_ad.html: localStorage
```

The solution: 
Find (CTRL + F) localStorage mentioning in the code: 

![image](https://user-images.githubusercontent.com/10512039/176189011-a04e92a7-734a-4afc-84ea-1be16a4e331f.png)

Change to:

![image](https://user-images.githubusercontent.com/10512039/176189299-35dd46bf-d6aa-4e27-aeb2-a6b3141f1215.png)

After that varification can be passed.

**Comment by yaustar** [comment]
I can't see it in the minified source of the engine either

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/16639049/176214229-857d2594-db5d-419d-97f8-3efe2bd95259.png">

**Comment by yaustar** [comment]
Ah yes, it is in the compressor: https://raw.githubusercontent.com/playcanvas/playcanvas-rest-api-tools/main/library-files/lz4.js

We could just modify that file to do a no-op/null instead
