### ISSUE TITLE
Custom Shader Issue

### ISSUE THREAD

**Issue by EvanSC1993** [playcanvas/playcanvas-rest-api-tools#40]
When i use this

ShaderChunkTest.attributes.add("shaderFrag", { type: "asset" });
var frag = this.shaderFrag.resource;

Then it is not work

When i use this
   var  frag = `
            uniform float iGlobalTime;
            void getOpacity()
            {
                if(vPositionW.x + iGlobalTime * 0.4 > 0.0)
                {
                    dAlpha = 0.4;
                }
                else
                {
                    dAlpha = 0.0;
                }
            }
            `;
It works

But all of them can work in editor Launch

What causes this problem？

Looking forward to your reply，Thank you!

**Comment by yaustar** [comment]
Can you provide an example project to test against please?

**Comment by EvanSC1993** [comment]
> Can you provide an example project to test against please?

Example Project : https://playcanvas.com/project/975277/overview/shaderchunktest

**Comment by yaustar** [comment]
What do you mean by 'Then it is not work'?

Also, I forgot to ask, which job/target are you using in the tool set? Eg are you making a playable ad with one-page?

**Comment by yaustar** [comment]
In which case, I can't reproduce the issue. The HTML I generate looks the same as the Editor launch tab
[Shader Issue.html.zip](https://github.com/playcanvas/playcanvas-rest-api-tools/files/9459976/Shader.Issue.html.zip)

**Comment by EvanSC1993** [comment]
[ShaderChunkTest.html.zip](https://github.com/playcanvas/playcanvas-rest-api-tools/files/9486372/ShaderChunkTest.html.zip)
Here are my results

**Comment by yaustar** [comment]
Can you post your config.json please?

**Comment by EvanSC1993** [comment]
Yes
Mine are:

{
    "playcanvas": {
        "project_id": 975277,
        "name": "ShaderChunkTest",
        "scenes" : [1515182],
        "branch_id": "c36cb0f2-a690-43dc-ac76-57acc3c90a47",
        "description": "",
        "preload_bundle": false,
        "version": "",
        "release_notes": "",
        "scripts_concatenate": true,
        "scripts_sourcemaps": false,
        "scripts_minify": true,
        "optimize_scene_format": false,
        "engine_version": ""
    },
    "csp": {
        "style-src": [
            "'self'",
            "'unsafe-inline'"
        ],
        "connect-src": [
            "'self'",
            "blob:",
            "data:",
            "https://www.google-analytics.com"
        ],
        "patch_preload_bundles": false
    },
"one_page": {
        "patch_xhr_out": true,
        "inline_game_scripts": true,
        "extern_files": false
    }
}

**Comment by yaustar** [comment]
Thanks, looks like the issue is related to using `patch_xhr_out`

**Comment by yaustar** [comment]
Found the issue, it looks like the glsl asset file wasn't being treated as text so the resource just a binary blob
