### ISSUE TITLE
[Error] node-gyp and lz4

### ISSUE THREAD

**Issue by kidcry0x** [playcanvas/playcanvas-rest-api-tools#46]
- **Node version:** 16.20.2, 18.18.2, 20.9.0 (I tested all 3 versions and got errors)
- **Python version:** 3.12.0

- I got an error after launching npm install, it seems to come from the lz4 module

![image](https://github.com/playcanvas/playcanvas-rest-api-tools/assets/61981331/84fecd87-30d5-4cab-80c3-c8cf219e049b)
![image](https://github.com/playcanvas/playcanvas-rest-api-tools/assets/61981331/7c31b76a-fe6e-497e-8041-59ea812f31e1)

**Comment by yaustar** [comment]
Actually, looking at this again, I wonder if I can just add the compiled LZ4 library code as a module instead of a package 🤔

**Comment by willeastcott** [comment]
Why not just switch to `lz4-napi` as you suggested? Looks kinda similar and is supported + maintained.

**Comment by yaustar** [comment]
I would need to really check but as I can tell, `lz4-napi` doesn't have a browser UMD to unpack to add to the playable ad build.

**Comment by yaustar** [comment]
Working on this at the moment and have a 'fix' by using a pure JS library

**Comment by willeastcott** [comment]
Great stuff! 🎉
